In [639]:
import pandas as pd


df = pd.read_csv("C:\\Users\\syjy0\\OneDrive\\바탕 화면\\전북대_산공\\GITHUB\Open-Course\\UMICH-Introduction to Data Science in Python\\olympics.csv", index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names = df.index.str.split('\s\(')

df.index = names.str[0] # the [0] element is the country name (new index) 
df['ID'] = names.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)
df = df.drop('Totals')


df

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,AFG
Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,ALG
Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,ARG
Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,ARM
Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,ANZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yugoslavia,16,26,29,28,83,14,0,3,1,4,30,26,32,29,87,YUG
Independent Olympic Participants,1,0,1,2,3,0,0,0,0,0,1,0,1,2,3,IOP
Zambia,12,0,1,1,2,0,0,0,0,0,12,0,1,1,2,ZAM
Zimbabwe,12,3,4,1,8,1,0,0,0,0,13,3,4,1,8,ZIM
Mixed team,3,8,5,4,17,0,0,0,0,0,3,8,5,4,17,ZZX

In [124]:
# Q0. What is the first country in df? a Series.

df.iloc[0]

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

In [133]:
#Q1. Which country has won the most gold medals in summer games?
    #-->a single string value.

#df['Gold'].argmax() # 'argmax() is fuction to find most values'
#idxmax(): 열에서 제일 큰 값을 가진 행을 찾아준다.

df['Gold'].idxmax()

'United States'

In [139]:
# Q2. Which country had the biggest difference between their summer and winter gold medal counts?
# -->This function should return a single string value.

(df['Gold']-df['Gold.1']).idxmax()

'United States'

In [645]:
# Q3. Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count?
#    Only include countries that have won at least 1 gold in both summer and winter.
gold=df[(df['Gold.1']>=1) & (df['Gold']>=1)]
gold['D']=abs((df['Gold']-df['Gold.1']))/df['Gold.2']

gold['D'].idxmax()

C:\Users\syjy0\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

'Bulgaria'

In [289]:
# Q4. Write a function that creates a Series called "Points"
#   (Gold.2):3 points,(Silver.2): 2 points,(Bronze.2):1 point 
#ANSWER: only the column (a Series object) which you created, with the country names as indices.
#       a Series named Points of length 146
 
Points=df['Gold.2']*3+df['Silver.2']*2+df['Bronze.2']*1

Points

KeyError: 'Column not found: Gold.2'

In [183]:
#Q5. Which state has the most counties in it? 
#    (hint: consider the sumlevel key carefully! You'll need this for future questions too...)
#    ANSWER: a single string value.

census= pd.read_csv('census.csv')
census

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

In [290]:
census['SUMLEV']==50
census

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

In [292]:
#groupby(): 같은 값을 하나로 묶어 통계 또는 집계 결과를 얻기 위해 사용하는 것
#groupby만 사용했을때는 값이 안나오고 뒤에 평균함수나 또 다른 함수를 사용해야 함
#
#to_frame('name'): name(맨 오른쪽으로 무조건 정렬 됨)으로 프레임만들어 주기
#reset_index(): 기본값으로 인데스 값들을 DataFrame의 열로 전송 + 새로운 단순한 정수 인덱스를 세팅
q5=census.groupby(["SUMLEV","STNAME"]).size().to_frame('count').reset_index()
q5

     SUMLEV         STNAME  count
0        40        Alabama      1
1        40         Alaska      1
2        40        Arizona      1
3        40       Arkansas      1
4        40     California      1
..      ...            ...    ...
97       50       Virginia    133
98       50     Washington     39
99       50  West Virginia     55
100      50      Wisconsin     72
101      50        Wyoming     23

[102 rows x 3 columns]

In [293]:
q5['count']

0        1
1        1
2        1
3        1
4        1
      ...
97     133
98      39
99      55
100     72
101     23
Name: count, Length: 102, dtype: int64

In [294]:
q5['count'].idxmax()

94

In [295]:
#loc[label]: 레이블을 기반으로 인덱싱을 한다.
q5.loc[a['count'].idxmax()]

SUMLEV       50
STNAME    Texas
count       254
Name: 94, dtype: object

In [296]:
#out287에서 원하는 행이름을 원하면 ['원하는 이름']을 추가
q5.loc[a['count'].idxmax()]['STNAME']

'Texas'

In [437]:
# Q6. Only looking at the three most populous counties for each state, what are the three most populous states (in order of highest population to lowest population)? 
# Use CENSUS2010POP.
# ANSWER: a list of string values.

In [426]:
# sort_values: (정렬할 기준변수(왼쪽부터 차례대로 정렬)/ascednding= true:오름차순, false:내림차순)
q6=census.sort_values(['STNAME','CENSUS2010POP'],ascending=False).groupby('STNAME').head()
q6

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
3169,40,4,8,56,0,Wyoming,Wyoming,563626,563767,564516,...,-0.381530,9.636214,4.487115,-4.788275,-3.221091,0.289680,10.694870,5.440390,-3.727831,-2.091573
3180,50,4,8,56,21,Wyoming,Laramie County,91738,91881,92271,...,-1.200428,15.547274,4.787847,-1.226133,0.278940,-0.973320,17.914554,6.003143,-0.207819,1.673640
3182,50,4,8,56,25,Wyoming,Natrona County,75450,75450,75472,...,7.189319,23.066162,24.322042,-0.958472,-0.061057,7.689674,23.749508,25.085233,-0.110593,0.793743
3172,50,4,8,56,5,Wyoming,Campbell County,46133,46133,46244,...,-2.843479,15.601020,-5.895711,-8.550911,10.916963,-2.649606,15.558684,-5.916543,-8.509402,10.978525
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
37,50,3,6,1,73,Alabama,Jefferson County,658466,658350,658116,...,-4.138628,-4.492646,-1.664873,-0.970225,-3.337536,-2.985041,-3.536344,-0.647113,0.221333,-2.126089
49,50,3,6,1,97,Alabama,Mobile County,412992,413143,413332,...,-5.242052,-3.722733,-3.181655,-2.311087,-3.873201,-3.751237,-2.281051,-1.753896,-0.759909,-2.288272
45,50,3,6,1,89,Alabama,Madison County,334811,334811,336138,...,4.170416,3.438521,6.367708,4.064107,2.480087,5.739131,4.880766,7.818211,5.734524,4.180881
51,50,3,6,1,101,Alabama,Montgomery County,229363,229363,229723,...,0.793549,-17.053618,-16.353778,-8.910671,-5.820167,2.441356,-15.057012,-14.486528,-6.784461,-3.598965

In [433]:
#위의 표에서groupby로 'STNAME'으로 정렬하고 sum으로 groupby에서 정리한 종류에 관해 다 더해서 정렬한다.=>위,아래 비교하며 이해할 것
q6=q6.groupby('STNAME').sum()
q6

,SUMLEV,REGION,DIVISION,STATE,COUNTY,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
STNAME,,,,,,,,,,,,,,,,,,,,,
Alabama,240,15,30,5,360,6415368,6415794,6422470,6443019,6459525,...,-4.414420,-22.023671,-14.451532,-7.545874,-11.018185,2.474225,-15.166996,-7.686044,0.136205,-3.119850
Alaska,240,20,45,10,402,1244033,1244051,1251049,1265415,1280963,...,-1.389371,10.606161,-8.467403,-47.876510,-21.979049,6.012144,25.953475,4.110548,-35.781418,-7.838881
Arizona,240,20,40,20,78,11776200,11776712,11806181,11917892,12086512,...,-6.539376,28.429989,27.913019,51.057317,52.668670,2.301828,37.887007,38.106825,62.810028,64.456257
Arkansas,240,15,35,25,400,3848814,3848895,3858842,3888062,3910546,...,23.145236,13.836104,12.477557,6.734513,19.165448,32.718511,24.059640,23.166202,18.827362,31.224602
California,240,20,45,30,234,55367747,55368537,55484626,56032409,56567748,...,2.563536,0.544455,-2.461745,-2.669608,-9.004967,21.332395,19.770000,17.477958,19.683039,13.739979
Colorado,240,20,40,40,136,7358163,7358364,7388822,7501440,7613585,...,36.293086,31.497338,35.843392,36.442390,45.141702,46.802961,45.951598,49.387002,51.138410,60.476312
Connecticut,240,5,5,45,24,6521472,6521517,6532232,6552888,6564243,...,-22.693977,-22.670198,-26.415801,-39.657442,-41.095972,1.106511,0.655383,-2.554214,-12.113901,-13.131184
Delaware,190,12,20,40,9,1795868,1795872,1799582,1815832,1834198,...,17.913309,21.883212,20.858193,29.279914,28.016833,27.002440,32.366305,30.902163,40.555969,39.377191
District of Columbia,90,6,10,22,1,1203446,1203534,1210252,1240944,1270684,...,23.120142,20.104888,18.915356,2.960189,11.203666,34.056844,31.944221,31.268241,16.756073,24.869676
Florida,240,15,25,60,253,25595171,25600146,25669326,26083091,26421697,...,43.030044,9.122183,3.052082,13.552422,19.917774,84.631047,47.039067,43.118392,58.864473,64.629566
Georgia,240,15,25,65,412,12793526,12794551,12829927,12982933,13151699,...,10.716688,24.886974,-0.121601,14.036986,14.328386,31.484747,45.275306,21.712005,38.850684,38.912563
Hawaii,240,20,45,75,20,2720512,2720512,2727870,2756364,2785193,...,-1.475491,-4.805857,9.043813,3.926124,-8.720674,21.890535,23.480362,37.067562,34.236004,22.325984
Idaho,240,20,40,80,102,2391598,2391738,2397456,2423548,2448095,...,19.269677,19.880134,36.946429,43.589453,45.649967,22.613104,23.640425,41.006589,48.360765,50.546901
Illinois,240,10,15,85,368,20323253,20324446,20341901,20383728,20419717,...,-30.131485,-29.337074,-24.379395,-34.563900,-39.407287,-18.421309,-16.429812,-10.985498,-19.148002,-23.508034
Indiana,240,10,15,90,246,8513098,8513583,8523636,8564616,8600843,...,0.455217,-1.939451,7.643342,-2.932934,-6.728629,9.862272,7.709230,18.068138,8.932031,5.127197
Iowa,240,10,20,95,442,3984535,3985044,3991558,4015789,4036576,...,7.835736,2.872326,9.979929,6.157051,-0.704968,15.623041,11.308577,19.091826,16.469306,9.521238
Kansas,240,10,20,100,650,4231101,4231115,4239959,4260966,4288891,...,-17.263747,-9.252519,-15.440525,-15.777825,-15.778536,-7.472661,2.155672,-3.648907,-2.463961,-2.336432
Kentucky,240,15,30,105,310,5654797,5654769,5666247,5697629,5724304,...,11.570534,5.654000,6.195920,-3.322743,-4.021859,21.563320,17.138002,18.141045,10.239480,9.500958
Louisiana,240,15,35,110,172,6004893,6005007,6022006,6068554,6109581,...,16.697218,4.734850,-7.815277,-21.658896,-17.502927,27.516128,16.043244,3.499458,-8.943196,-4.677577
Maine,240,5,5,115,66,2083240,2083239,2082329,2084849,2087287,...,3.736566,0.338629,-3.051458,9.741138,-6.646738,8.035648,5.003458,1.865296,15.379210,-0.994127
Maryland,240,15,25,120,579,9034739,9035206,9057851,9146518,9221421,...,-10.648267,-14.788447,-15.411318,-20.609947,-31.498415,18.236047,12.693714,13.792690,12.084234,1.086175
Massachusetts,240,5,5,125,78,10314448,10314747,10343535,10427792,10511467,...,-4.820605,-6.378775,-4.165507,-12.805444,-19.433579,28.042289,26.187131,30.359703,26.425097,19.390229
Michigan,240,10,15,130,468,14350186,14350741,14339737,14340185,14364102,...,-18.258869,-7.484237,-6.881379,-11.506430,-18.929227,-6.806728,5.185021,6.848825,4.087612,-3.416698
Minnesota,240,10,20,135,216,7694386,7694349,7705222,7768355,7827294,...,-4.549973,-3.750307,0.331678,-6.378964,-15.841109,11.333982,12.042162,17.266349,12.661055,3.056987
Mississippi,240,15,30,140,250,3702556,3703898,3708192,3725217,3739468,...,20.403357,8.593541,-0.091357,0.386897,-2.050191,24.239857,15.654886,5.222546,5.862646,4.095330
Missouri,240,10,20,145,977,8341818,8341891,8350975,8369317,8391932,...,-19.576416,-14.130960,-11.051905,-11.528295,-10.651893,-10.608984,-4.521969,-0.779773,0.115935,0.991444
Montana,240,20,40,150,234,1427127,1427129,1428998,1440308,1452367,...,21.913910,23.301144,42.414371,45.662067,54.052379,25.509254,26.312082,45.639006,49.306133,57.636359
Nebraska,240,10,20,155,396,2846305,2846311,2853445,2879302,2907359,...,10.598056,9.484514,8.863089,4.962931,-5.510592,24.486639,26.257217,25.356602,23.153229,12.971057
Nevada,240,20,40,160,563,5180481,5180641,5186053,5217343,5287964,...,-22.783754,6.699359,9.459196,39.528657,45.412649,-14.496687,14.604387,18.106104,49.624991,55.607516
New Hampshire,240,5,5,165,56,2282002,2281995,2282706,2286878,2293482,...,-3.221692,1.755079,-10.538283,13.517026,0.478239,3.335279,8.441573,-3.614390,21.572959,8.529201
New Jersey,240,5,10,170,56,11925103,11925177,11942939,12009824,12064084,...,-28.719284,-33.459020,-31.539333,-40.877749,-45.607439,13.986454,6.193113,11.222272,7.546449,2.393847
New Mexico,240,20,40,175,106,3206707,3206722,3215873,3240310,3253891,...,14.740954,-1.081774,-14.118935,-14.866379,-11.570428,20.669080,6.003294,-6.954793,-6.450171,-2.845700
New York,240,5,10,180,292,27192747,27192503,27232315,27439528,27585937,...,-22.484281,-34.403815,-35.504253,-51.119077,-47.492797,16.290654,2.113654,4.161318,-6.123642,-2.784579
North Carolina,240,15,25,185,450,12195180,12195455,12230210,12375103,12526973,...,30.942823,34.774969,32.311248,32.307578,28.250539,46.060010,49.795112,48.045723,50.002497,45.881930
North Dakota,240,10,20,190,168,1032213,1032213,1035626,1052743,1078832,...,36.589194,56.719353,103.641976,46.121011,48.478071,46.437533,75.812007,119.191733,61.687456,65.014457
Ohio,240,10,15,195,298,15324195,15324539,15329229,15337254,15358779,...,-23.520681,-13.657223,-8.688987,-9.731089,-16.728486,-12.614560,-2.151258,3.593288,4.314177,-2.775109
Oklahoma,240,15,35,200,310,5453240,5453542,5468200,5513414,5568121,...,7.396135,7.531520,-0.871849,-7.843186,0.271597,17.268067,24.271905,12.677970,6.321271,15.547125
Oregon,240,20,45,205,162,5823825,5823824,5835822,5889821,5944556,...,19.203974,21.051826,15.816921,32.204349,44.815797,29.516431,31.234551,27.071720,45.235921,57.777445
Pennsylvania,240,5,10,210,212,16876856,16877380,16890821,16943976,16990149,...,-1.919941,-6.673788,-10.508507,-16.367302,-18.393623,11.389272,7.604001,4.699665,1.188148,-0.885573
Rhode Island,240,5,5,220,24,2055259,2055987,2056574,2054439,2055563,...,-25.937962,-23.004453,-18.853620,-9.544074,-16.504712,-12.483621,-7.367490,-4.091034,6.883191,0.715059
South Carolina,240,15,25,225,226,6095609,6095635,6110323,6165192,6235334,...,24.543634,35.154783,35.315402,42.313881,50.712704,31.750981,43.716824,42.681465,50.324957,59.325605
South Dakota,240,10,20,230,298,1165955,1165958,1169498,1182497,1200595,...,29.898419,54.469163,55.127067,32.572346,5.250847,39.093254,65.373084,65.700243,44.052877,16.735934
Tennessee,240,15,30,235,352,8669119,8669276,8683682,8745184,8831308,...,12.418323,28.117168,5.935101,5.638775,4.880285,21.989123,37.663737,15.972897,17.138261,16.448201
Texas,240,15,35,240,782,35129966,35131129,35265531,35849392,36480861,...,19.532167,27.879689,19.339331,24.257344,23.196212,38.367034,46.920679,39.305354,46.786881,45.737464
Utah,240,20,40,245,152,4847819,4847824,4868731,4941837,5013961,...,-5.285323,-2.333824,8.665984,-0.666269,12.977845,2.674051,6.410103,17.685249,9.452264,23.132459
Vermont,240,5,5,250,78,960132,960123,960567,961904,961656,...,-4.542357,-20.141402,-7.074340,-15.775675,-22.123927,-0.015713,-14.644371,-1.253000,-9.017434,-15.322920
Virginia,240,15,25,255,1063,10238982,10238899,10275343,10400018,10515301,...,16.653851,0.462139,-1.194430,-22.208576,-26.478272,39.069197,27.202521,23.640311,4.989925,1.676114
Washington,240,20,45,265,210,10635570,10635579,10663823,10795075,10927203,...,9.113064,12.110390,17.715740,24.903617,27.825554,24.599880,30.826277,36.138208,45.208964,48.317523
West Virginia,240,15,25,270,114,2342734,2342746,2344965,2347852,2352856,...,15.489668,20.930204,11.438166,3.213295,-0.069736,21.319885,27.345228,18.014343,10.691221,7.363060
Wisconsin,240,10,15,275,246,7760692,7761045,7766275,7799288,7830828,...,0.162288,1.808643,-5.110207,-6.433422,-10.168576,8.495000,11.051809,4.875186,5.214867,1.459067
Wyoming,240,20,40,280,88,820753,821037,822096,827492,843658,...,3.836524,80.093869,22.361520,-29.776681,-6.335108,5.611649,84.160815,25.316763,-26.630927,-2.715859

In [436]:
# 거의 마지막단계인 위 표에서 다시' CENSUS2010POP'에관해서 내림차순으로 정리/ head(3):위에서 3번째까지 정렬
q6=q6.sort_values(['CENSUS2010POP'],ascending=False).head(3)
q6

,SUMLEV,REGION,DIVISION,STATE,COUNTY,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
STNAME,,,,,,,,,,,,,,,,,,,,,
California,240,20,45,30,234,55367747,55368537,55484626,56032409,56567748,...,2.563536,0.544455,-2.461745,-2.669608,-9.004967,21.332395,19.770000,17.477958,19.683039,13.739979
Texas,240,15,35,240,782,35129966,35131129,35265531,35849392,36480861,...,19.532167,27.879689,19.339331,24.257344,23.196212,38.367034,46.920679,39.305354,46.786881,45.737464
New York,240,5,10,180,292,27192747,27192503,27232315,27439528,27585937,...,-22.484281,-34.403815,-35.504253,-51.119077,-47.492797,16.290654,2.113654,4.161318,-6.123642,-2.784579

In [438]:
list(q6.index.values)

['California', 'Texas', 'New York']

In [471]:
#Q7. Which county has had the largest absolute change in population within the period 2010-2015? 
#    (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)
#    e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.
# ANSWER: a single string value.

In [604]:
#정렬할 대상 축을 결정할 때에는 axis 를 이용합니다. 
#axis=0 라고 써주면 인덱스를 기준으로 정렬하며(기본값), 
#axis=1 라고 써주면 컬럼을 기준으로 정렬합니다.
#std: 표준편차
q7['STDEV'] = q7[['POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012',
                      'POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']].std(axis=1)
q7.loc[q7['STDEV'].idxmax()]['CTYNAME']

C:\Users\syjy0\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

'Harris County'

In [633]:
#Q8. In this datafile, the United States is broken up into four regions using the "REGION" column.
#    Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.
#ANSWER: a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).

q8=census
r1=census['REGION']==1
r2=census['REGION']==2
name=census['CTYNAME'].str.startswith('Washington')
pop=census['POPESTIMATE2015']>census['POPESTIMATE2014']
q8

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

In [637]:
print(r1)
print(r2)
q8=q8[(r2|r1)]
q8

0       False
1       False
2       False
3       False
4       False
        ...
3188    False
3189    False
3190    False
3191    False
3192    False
Name: REGION, Length: 3193, dtype: bool
0       False
1       False
2       False
3       False
4       False
        ...
3188    False
3189    False
3190    False
3191    False
3192    False
Name: REGION, Length: 3193, dtype: bool

C:\Users\syjy0\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
896,50,2,4,19,183,Iowa,Washington County,21704,21704,21697,...,5.743693,2.468684,-0.364282,0.272171,1.849596,5.881542,2.560117,-0.273212,0.408256,1.984933
1419,50,2,4,27,163,Minnesota,Washington County,238136,238134,238995,...,2.555118,3.260957,2.285952,3.072543,0.678755,4.178076,4.907905,4.009584,5.040262,2.615204
2345,50,1,2,42,125,Pennsylvania,Washington County,207820,207820,207877,...,3.683135,3.260434,1.219337,2.113561,1.656917,4.062988,3.750219,1.742595,2.762039,2.305276
2355,50,1,1,44,9,Rhode Island,Washington County,126979,127094,127085,...,-4.669304,-2.659574,1.551904,1.400112,0.506035,-3.533527,-1.788880,2.462459,2.428442,1.533918
3163,50,2,3,55,131,Wisconsin,Washington County,131887,131885,131967,...,-0.794876,0.785279,-2.215465,1.601149,-0.434498,-0.431504,1.162817,-1.763330,2.104796,0.059931

In [635]:
# ***이렇게도 데이터를 가져오는 구나***
q8=q8[(r2|r1)&name&pop]
q8

C:\Users\syjy0\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
896,50,2,4,19,183,Iowa,Washington County,21704,21704,21697,...,5.743693,2.468684,-0.364282,0.272171,1.849596,5.881542,2.560117,-0.273212,0.408256,1.984933
1419,50,2,4,27,163,Minnesota,Washington County,238136,238134,238995,...,2.555118,3.260957,2.285952,3.072543,0.678755,4.178076,4.907905,4.009584,5.040262,2.615204
2345,50,1,2,42,125,Pennsylvania,Washington County,207820,207820,207877,...,3.683135,3.260434,1.219337,2.113561,1.656917,4.062988,3.750219,1.742595,2.762039,2.305276
2355,50,1,1,44,9,Rhode Island,Washington County,126979,127094,127085,...,-4.669304,-2.659574,1.551904,1.400112,0.506035,-3.533527,-1.788880,2.462459,2.428442,1.533918
3163,50,2,3,55,131,Wisconsin,Washington County,131887,131885,131967,...,-0.794876,0.785279,-2.215465,1.601149,-0.434498,-0.431504,1.162817,-1.763330,2.104796,0.059931

In [636]:
q8[['STNAME', 'CTYNAME']]

            STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County