In [1]:
# Q1.-1
# Load the energy data from the file `Energy Indicators.xls`
# Call this DataFrame **energy**. 
# - The first two columns are unneccessary, so you should get rid of them.
# - change the column labels so that the columns are ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
# - rename 
#"Republic of Korea": "South Korea",
#"United States of America": "United States",
#"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
#"China, Hong Kong Special Administrative Region": "Hong Kong"

# Q1.-2
# Load the GDP data from the file `world_bank.csv`
# Call this DataFrame **GDP**. 
# Make sure to skip the header, and rename the following list of countries:
# "Korea, Rep.": "South Korea", 
# "Iran, Islamic Rep.": "Iran",
# "Hong Kong SAR, China": "Hong Kong"

# Q1-3
# Load the 'scimagojr-3.xlsx'
# Call this DataFrame **ScimEn**. 


#Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). 
#Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15). 
#The index of this DataFrame should be the name of the country, and the columns should be ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
#       'Citations per document', 'H index', 'Energy Supply',
#       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
#       '2009', '2010', '2011', '2012', '2013', '2014', '2015'].


#ANSWER: DataFrame with 20 columns and 15 entries.

In [2]:
import pandas as pd
import numpy as np
#엑셀파일을 보고 필요한 부분을 가져오도록 하자: 도구skip_footer/skiprows/parse_cols
#skipfooter: 파일의 맨 아래에서부터의 건너 뛸 줄 수
energy=pd.read_excel('C:\\Users\\syjy0\\OneDrive\\바탕 화면\\전북대_산공\\GITHUB\\Open-Course\\UMICH-Introduction to Data Science in Python/Energy Indicators.xls',skiprows=17,skipfooter=38)
energy=energy.drop(['Unnamed: 0','Unnamed: 1'],axis=1)
energy

                    Unnamed: 2 Petajoules Gigajoules           %
0                  Afghanistan        321         10   78.669280
1                      Albania        102         35  100.000000
2                      Algeria       1959         51    0.551010
3               American Samoa        ...        ...    0.641026
4                      Andorra          9        121   88.695650
..                         ...        ...        ...         ...
222                   Viet Nam       2554         28   45.321520
223  Wallis and Futuna Islands          0         26    0.000000
224                      Yemen        344         13    0.000000
225                     Zambia        400         26   99.714670
226                   Zimbabwe        480         32   52.536120

[227 rows x 4 columns]

In [3]:
energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
energy

,Country,Energy Supply,Energy Supply per Capita,% Renewable
0,Afghanistan,321,10,78.669280
1,Albania,102,35,100.000000
2,Algeria,1959,51,0.551010
3,American Samoa,...,...,0.641026
4,Andorra,9,121,88.695650
...,...,...,...,...
222,Viet Nam,2554,28,45.321520
223,Wallis and Futuna Islands,0,26,0.000000
224,Yemen,344,13,0.000000
225,Zambia,400,26,99.714670
226,Zimbabwe,480,32,52.536120

In [4]:
#F or all countries which have missing data (e.g. data with "...") make sure this is reflected as `np.NaN` values.
energy.loc[energy['Energy Supply'] == '...'] = np.NaN

# .str.replace('찾을 내용`, `바꿀 내용`)+정규식 이용
#국가명 뒤에 (~~)붙은거 제거
energy['Country'] = energy['Country'].str.replace(r" \(.*\)","")

#국가명 뒤에 숫자 제거
energy['Country'] = energy['Country'].str.replace(r"([0-9]+)$","")

# .apply(pd.to_numeric): 문자열 칼럼을 숫자형으로 변환
energy[['Energy Supply', 'Energy Supply per Capita']] = energy[['Energy Supply', 'Energy Supply per Capita']].apply(pd.to_numeric)

# Convert `Energy Supply` to gigajoules,there are 1,000,000 gigajoules in a petajoule
energy['Energy Supply'] = energy['Energy Supply']*10**6

replace_dict={"Republic of Korea": "South Korea",
              "United States of America": 'United States',
              "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
              "China, Hong Kong Special Administrative Region": "Hong Kong"}
energy['Country'].replace(to_replace=replace_dict, inplace=True)

#The index of this DataFrame should be the name of the country
energy = energy.set_index('Country')

energy

,Energy Supply,Energy Supply per Capita,% Renewable
Country,,,
Afghanistan,3.210000e+08,10.0,78.66928
Albania,1.020000e+08,35.0,100.00000
Algeria,1.959000e+09,51.0,0.55101
NaN,NaN,NaN,NaN
Andorra,9.000000e+06,121.0,88.69565
...,...,...,...
Viet Nam,2.554000e+09,28.0,45.32152
Wallis and Futuna Islands,0.000000e+00,26.0,0.00000
Yemen,3.440000e+08,13.0,0.00000
Zambia,4.000000e+08,26.0,99.71467
Zimbabwe,4.800000e+08,32.0,52.53612

In [5]:
GDP=pd.read_csv('C:\\Users\\syjy0\\OneDrive\\바탕 화면\\전북대_산공\\GITHUB\\Open-Course\\UMICH-Introduction to Data Science in Python/world_bank.csv',skiprows=4)
replace_dict = {"Korea, Rep.": "South Korea", 
                "Iran, Islamic Rep.": "Iran",
                "Hong Kong SAR, China": "Hong Kong"}
GDP['Country Name'].replace(to_replace=replace_dict, inplace=True)
GDP=GDP.rename(columns={'Country Name':'Country'})

#The index of this DataFrame should be the name of the country
GDP = GDP.set_index('Country')

GDP

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN
Andorra,AND,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN
Afghanistan,AFG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,1.935220e+10,1.973134e+10,1.999032e+10,2.029415e+10
Angola,AGO,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.581103e+10,6.842044e+10,7.787420e+10,7.975320e+10,8.247091e+10,8.570262e+10,9.012096e+10,9.626143e+10,1.008863e+11,1.039106e+11
Albania,ALB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.771760e+09,1.034829e+10,1.112752e+10,1.150029e+10,1.192695e+10,1.223109e+10,1.240477e+10,1.254247e+10,1.279331e+10,1.312082e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Yemen, Rep.",YEM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.672565e+10,2.761787e+10,2.872656e+10,2.991436e+10,3.090675e+10,2.624342e+10,2.689160e+10,2.800914e+10,NaN,NaN
South Africa,ZAF,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,7.707081e+10,8.003449e+10,8.497844e+10,9.124438e+10,9.848904e+10,1.072507e+11,1.120109e+11,...,3.402852e+11,3.585261e+11,3.699668e+11,3.642764e+11,3.753494e+11,3.874074e+11,3.960071e+11,4.047682e+11,4.110369e+11,4.163117e+11
"Congo, Dem. Rep.",COD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.508024e+10,1.344383e+10,1.629401e+10,1.714358e+10,1.672524e+10,1.689205e+10,1.803656e+10,...,1.650894e+10,1.754232e+10,1.863448e+10,1.916651e+10,2.052329e+10,2.193213e+10,2.350200e+10,2.550050e+10,2.778776e+10,2.970961e+10
Zambia,ZMB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.592975e+09,4.655503e+09,4.539542e+09,4.688093e+09,5.260699e+09,6.136472e+09,5.794651e+09,...,1.440569e+10,1.560892e+10,1.682234e+10,1.837342e+10,2.026555e+10,2.140358e+10,2.302438e+10,2.420595e+10,2.542227e+10,2.624127e+10
Zimbabwe,ZWE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,3.338344e+09,3.549199e+09,3.600111e+09,3.824915e+09,3.782605e+09,3.968352e+09,4.028795e+09,...,1.006276e+10,9.695130e+09,7.982103e+09,8.459783e+09,9.422161e+09,1.054391e+10,1.165789e+10,1.218064e+10,1.264939e+10,1.278517e+10

In [6]:
ScimEn=pd.read_excel('C:\\Users\\syjy0\\OneDrive\\바탕 화면\\전북대_산공\\GITHUB\\Open-Course\\UMICH-Introduction to Data Science in Python/scimagojr-3.xlsx')

#The index of this DataFrame should be the name of the country
ScimEn = ScimEn.set_index('Country')

ScimEn

,Rank,Region,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
Country,,,,,,,,
China,1,Asiatic Region,235126,233883,1909601,1306438,8.12,224
United States,2,Northern America,157811,154288,1940563,639345,12.30,333
Japan,3,Asiatic Region,46032,45559,436961,109968,9.49,181
India,4,Asiatic Region,39893,38848,368175,123446,9.23,171
United Kingdom,5,Western Europe,38873,37780,536378,100038,13.80,208
...,...,...,...,...,...,...,...,...
Kiribati,201,Pacific Region,1,1,17,0,17.00,1
Comoros,202,Africa,1,1,0,0,0.00,0
Palau,203,Pacific Region,1,1,0,0,0.00,0
Montserrat,204,Latin America,1,1,2,0,2.00,1
Sao Tome and Principe,205,Africa,1,1,0,0,0.00,0

In [7]:
#left_index=True, right_index=True:우리는 여기서 index를 3개의 DF다 'COUNTRY'로 지정
#따라서, '왼쪽(첫번째 DF),오른쪽(두번째 DF)의 색인으로 합치겠다'라는 뜻
Merge=pd.merge(energy,GDP,how='outer',left_index=True, right_index=True)
Merge2=pd.merge(Merge,ScimEn,how='outer',left_index=True, right_index=True)
Merge2=Merge2[['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015']]
Merge2

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
Afghanistan,139.0,25.0,24.0,73.0,7.0,2.92,5.0,3.210000e+08,10.0,78.66928,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,1.935220e+10,1.973134e+10,1.999032e+10,2.029415e+10
Albania,119.0,57.0,57.0,363.0,27.0,6.37,10.0,1.020000e+08,35.0,100.00000,9.771760e+09,1.034829e+10,1.112752e+10,1.150029e+10,1.192695e+10,1.223109e+10,1.240477e+10,1.254247e+10,1.279331e+10,1.312082e+10
Algeria,42.0,3205.0,3111.0,26589.0,5320.0,8.30,66.0,1.959000e+09,51.0,0.55101,1.446474e+11,1.495654e+11,1.531550e+11,1.556055e+11,1.612073e+11,1.658823e+11,1.715223e+11,1.763249e+11,1.830252e+11,1.901632e+11
American Samoa,179.0,3.0,3.0,2.0,0.0,0.67,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Andorra,181.0,2.0,2.0,24.0,0.0,12.00,1.0,9.000000e+06,121.0,88.69565,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#dropna함수는 column내에 NaN값이 있으면 해당 내용은 필요없다 간주하고 삭제해버린다.
#threshthreshold(임계값)을 설정할 수 있는데, NaN이 ~개 이상 있는 것에 대해서만 삭제해버린다는 의미
print(Merge2.shape)
print(Merge2.shape[1])
print(Merge2.shape[1]-10)

#2016 IranGDP가 Nan이나오기 때문에 2006~2015사이에 Nan이 나오는 것을 제외시켜줘야한다.
#shape(행,열) 따라서 shape(0)=행, shape(1)=열
Merge2=Merge2.dropna(thresh=Merge2.shape[1]-10)
print(Merge2.shape)
Merge2

(324, 20)
20
10
(256, 20)

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
Afghanistan,139.0,25.0,24.0,73.0,7.0,2.92,5.0,3.210000e+08,10.0,78.66928,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,1.935220e+10,1.973134e+10,1.999032e+10,2.029415e+10
Albania,119.0,57.0,57.0,363.0,27.0,6.37,10.0,1.020000e+08,35.0,100.00000,9.771760e+09,1.034829e+10,1.112752e+10,1.150029e+10,1.192695e+10,1.223109e+10,1.240477e+10,1.254247e+10,1.279331e+10,1.312082e+10
Algeria,42.0,3205.0,3111.0,26589.0,5320.0,8.30,66.0,1.959000e+09,51.0,0.55101,1.446474e+11,1.495654e+11,1.531550e+11,1.556055e+11,1.612073e+11,1.658823e+11,1.715223e+11,1.763249e+11,1.830252e+11,1.901632e+11
Andorra,181.0,2.0,2.0,24.0,0.0,12.00,1.0,9.000000e+06,121.0,88.69565,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN
Angola,110.0,81.0,81.0,363.0,6.0,4.48,10.0,6.420000e+08,27.0,70.90909,5.581103e+10,6.842044e+10,7.787420e+10,7.975320e+10,8.247091e+10,8.570262e+10,9.012096e+10,9.626143e+10,1.008863e+11,1.039106e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.016675e+09,7.878227e+09,7.201473e+09,8.709518e+09,8.913100e+09,9.611505e+09,1.100864e+10,1.053747e+10,1.042246e+10,1.171414e+10
World,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.023536e+13,6.282865e+13,6.398692e+13,6.291271e+13,6.564782e+13,6.770244e+13,6.937886e+13,7.104232e+13,7.291072e+13,7.470901e+13
Yemen,113.0,69.0,69.0,727.0,75.0,10.54,15.0,3.440000e+08,13.0,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zambia,120.0,56.0,56.0,143.0,9.0,2.55,7.0,4.000000e+08,26.0,99.71467,1.440569e+10,1.560892e+10,1.682234e+10,1.837342e+10,2.026555e+10,2.140358e+10,2.302438e+10,2.420595e+10,2.542227e+10,2.624127e+10
Zimbabwe,122.0,45.0,43.0,86.0,9.0,1.91,6.0,4.800000e+08,32.0,52.53612,1.006276e+10,9.695130e+09,7.982103e+09,8.459783e+09,9.422161e+09,1.054391e+10,1.165789e+10,1.218064e+10,1.264939e+10,1.278517e+10

In [9]:
Merge2=Merge2.loc[Merge2['Rank']<=15]
Merge2

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
Australia,14.0,18077.0,17661.0,263733.0,44799.0,14.59,161.0,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15.0,18024.0,17745.0,152380.0,37112.0,8.45,121.0,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12
Canada,8.0,29633.0,29011.0,491467.0,88987.0,16.59,210.0,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
China,1.0,235126.0,233883.0,1909601.0,1306438.0,8.12,224.0,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
France,11.0,22429.0,21913.0,300015.0,58151.0,13.38,169.0,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
Germany,6.0,32935.0,32227.0,367356.0,78265.0,11.15,186.0,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,4.0,39893.0,38848.0,368175.0,123446.0,9.23,171.0,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
Iran,12.0,19371.0,19085.0,242250.0,77012.0,12.51,127.0,9.172000e+09,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Italy,9.0,23725.0,22819.0,312631.0,76446.0,13.18,155.0,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Japan,3.0,46032.0,45559.0,436961.0,109968.0,9.49,181.0,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
Russian Federation,7.0,31880.0,31664.0,91906.0,42529.0,2.88,84.0,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
South Korea,10.0,23451.0,23166.0,279709.0,53110.0,11.93,146.0,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Spain,13.0,18882.0,18529.0,312632.0,56968.0,16.56,163.0,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
United Kingdom,5.0,38873.0,37780.0,536378.0,100038.0,13.80,208.0,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
United States,2.0,157811.0,154288.0,1940563.0,639345.0,12.30,333.0,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13

In [10]:
Merge2=Merge2.sort_values('Rank',ascending=True)
Merge2

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1.0,235126.0,233883.0,1909601.0,1306438.0,8.12,224.0,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2.0,157811.0,154288.0,1940563.0,639345.0,12.30,333.0,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3.0,46032.0,45559.0,436961.0,109968.0,9.49,181.0,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
India,4.0,39893.0,38848.0,368175.0,123446.0,9.23,171.0,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
United Kingdom,5.0,38873.0,37780.0,536378.0,100038.0,13.80,208.0,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Germany,6.0,32935.0,32227.0,367356.0,78265.0,11.15,186.0,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
Russian Federation,7.0,31880.0,31664.0,91906.0,42529.0,2.88,84.0,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,8.0,29633.0,29011.0,491467.0,88987.0,16.59,210.0,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Italy,9.0,23725.0,22819.0,312631.0,76446.0,13.18,155.0,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
South Korea,10.0,23451.0,23166.0,279709.0,53110.0,11.93,146.0,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
France,11.0,22429.0,21913.0,300015.0,58151.0,13.38,169.0,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
Iran,12.0,19371.0,19085.0,242250.0,77012.0,12.51,127.0,9.172000e+09,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Spain,13.0,18882.0,18529.0,312632.0,56968.0,16.56,163.0,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Australia,14.0,18077.0,17661.0,263733.0,44799.0,14.59,161.0,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15.0,18024.0,17745.0,152380.0,37112.0,8.45,121.0,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

In [11]:
#Q2 The previous question joined three datasets then reduced this to just the top 15 entries. When you joined the datasets, but before you reduced this to the top 15 items, how many entries did you lose?
#ANSWER: single number.

In [12]:
#Q3  What is the average GDP over the last 10 years for each country? (exclude missing values from this calculation.)
# Answer: a Series named avgGDP with 15 countries and their average GDP sorted in descending order.

In [13]:
avgGDP=Merge2[['2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015']].mean(axis=1)
avgGDP

Country
China                 6.348609e+12
United States         1.536434e+13
Japan                 5.542208e+12
India                 1.769297e+12
United Kingdom        2.487907e+12
Germany               3.493025e+12
Russian Federation    1.565459e+12
Canada                1.660647e+12
Italy                 2.120175e+12
South Korea           1.106715e+12
France                2.681725e+12
Iran                  4.441558e+11
Spain                 1.418078e+12
Australia             1.164043e+12
Brazil                2.189794e+12
dtype: float64

In [14]:
#Q4 By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?
#Answer: a single number.

In [15]:
lis=Merge2[['2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015']]
re=Merge2['2015']-Merge2['2006']
result=Merge2[['2006','2015']]

#평균GDP와 변화량을 데이터프레임에 새롭게 추가
result['change']=re
result['avgGDP']=lis.mean(axis=1)
result=result.sort_values('avgGDP', ascending=False)
result

C:\Users\syjy0\anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\syjy0\anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

                            2006          2015        change        avgGDP
Country
United States       1.479230e+13  1.654857e+13  1.756269e+12  1.536434e+13
China               3.992331e+12  8.797999e+12  4.805667e+12  6.348609e+12
Japan               5.496542e+12  5.669563e+12  1.730216e+11  5.542208e+12
Germany             3.332891e+12  3.685556e+12  3.526652e+11  3.493025e+12
France              2.607840e+12  2.761185e+12  1.533457e+11  2.681725e+12
United Kingdom      2.419631e+12  2.666333e+12  2.467027e+11  2.487907e+12
Brazil              1.845080e+12  2.319423e+12  4.743437e+11  2.189794e+12
Italy               2.202170e+12  2.049316e+12 -1.528541e+11  2.120175e+12
India               1.265894e+12  2.367206e+12  1.101312e+12  1.769297e+12
Canada              1.564469e+12  1.792609e+12  2.281399e+11  1.660647e+12
Russian Federation  1.385793e+12  1.616149e+12  2.303563e+11  1.565459e+12
Spain               1.414823e+12  1.419821e+12  4.998675e+09  1.418078e+12
Australia           1.021939e+12  1.301251e+12  2.793118e+11  1.164043e+12
South Korea         9.410199e+11  1.266580e+12  3.255605e+11  1.106715e+12
Iran                3.895523e+11           NaN           NaN  4.441558e+11

In [16]:
result.iloc[5]['change']

246702696075.3999

In [17]:
#Q5. What is the mean Energy Supply per Capita?

In [18]:
Merge2['Energy Supply per Capita'].mean()

157.6

In [19]:
#Q6. What country has the maximum % Renewable and what is the percentage?
#Answer: a tuple with the name of the country and the percentage.

In [20]:
country=Merge2['% Renewable'].idxmax()
percentage=Merge2.loc[country,'% Renewable']

(country,percentage)

('Brazil', 69.64803)

In [21]:
#Q7 Create a new column that is the ratio of Self-Citations to Total Citations. What is the maximum value for this new column, and what country has the highest ratio?
#Answer: a tuple with the name of the country and the ratio.

In [22]:
ratio=Merge2['Self-citations']/Merge2['Citations']
Merge2['ratio']=ratio
country=Merge2['ratio'].idxmax()
percentage=Merge2.loc[country,'ratio']

(country,percentage)

('China', 0.6841418704745127)

In [23]:
#Q8 Create a column that estimates the population using Energy Supply and Energy Supply per capita. 
#   What is the third most populous country according to this estimate?
# Answer: a single string value

In [68]:
Merge2['population']=Merge2['Energy Supply']/Merge2['Energy Supply per Capita']
Merge2=Merge2.sort_values(['population'],ascending=False)
Merge2=Merge2.reset_index()
Merge2

,index,Country,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,...,2008,2009,2010,2011,2012,2013,2014,2015,ratio,population
0,0,China,1.0,235126.0,233883.0,1909601.0,1306438.0,8.12,224.0,1.271910e+11,...,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,0.684142,1.367645e+09
1,1,India,4.0,39893.0,38848.0,368175.0,123446.0,9.23,171.0,3.319500e+10,...,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,0.335292,1.276731e+09
2,2,United States,2.0,157811.0,154288.0,1940563.0,639345.0,12.30,333.0,9.083800e+10,...,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,0.329464,3.176154e+08
3,3,Brazil,15.0,18024.0,17745.0,152380.0,37112.0,8.45,121.0,1.214900e+10,...,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,0.243549,2.059153e+08
4,4,Russian Federation,7.0,31880.0,31664.0,91906.0,42529.0,2.88,84.0,3.070900e+10,...,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,0.462745,1.435000e+08
5,5,Japan,3.0,46032.0,45559.0,436961.0,109968.0,9.49,181.0,1.898400e+10,...,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,0.251665,1.274094e+08
6,6,Germany,6.0,32935.0,32227.0,367356.0,78265.0,11.15,186.0,1.326100e+10,...,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,0.213049,8.036970e+07
7,7,Iran,12.0,19371.0,19085.0,242250.0,77012.0,12.51,127.0,9.172000e+09,...,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,0.317903,7.707563e+07
8,8,United Kingdom,5.0,38873.0,37780.0,536378.0,100038.0,13.80,208.0,7.920000e+09,...,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,0.186507,6.387097e+07
9,9,France,11.0,22429.0,21913.0,300015.0,58151.0,13.38,169.0,1.059700e+10,...,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,0.193827,6.383735e+07
10,10,Italy,9.0,23725.0,22819.0,312631.0,76446.0,13.18,155.0,6.530000e+09,...,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,0.244525,5.990826e+07
11,11,South Korea,10.0,23451.0,23166.0,279709.0,53110.0,11.93,146.0,1.100700e+10,...,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,0.189876,4.980543e+07
12,12,Spain,13.0,18882.0,18529.0,312632.0,56968.0,16.56,163.0,4.923000e+09,...,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,0.182221,4.644340e+07
13,13,Canada,8.0,29633.0,29011.0,491467.0,88987.0,16.59,210.0,1.043100e+10,...,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,0.181064,3.523986e+07
14,14,Australia,14.0,18077.0,17661.0,263733.0,44799.0,14.59,161.0,5.386000e+09,...,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,0.169865,2.331602e+07